{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "border0-connector.generatedClusterRoleName" . }}
  labels:
    {{- include "border0-connector.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "border0-connector.generatedServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "border0-connector.generatedClusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
