apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "border0-connector.generatedServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "border0-connector.labels" . | nindent 4 }}
