image:
  repository: ghcr.io/borderzero/border0
  tag: latest
  pullPolicy: Always
  override: null

serviceAccount:
  name: border0-connector

rbac:
  create: true
  name: border0-connector

config:
  # Provide either a token OR an inviteCode
  # If inviteCode is provided, the connector will exchange it for a token
  # and persist it in the Kubernetes secret
  token: ""
  inviteCode: ""

  # Kubernetes secret configuration (used when inviteCode is provided)
  # The secret will be automatically updated with the exchanged token
  secretName: "connector-config"
